### PR TITLE
Updated dependencies for bootstrap and bootstrap-switch

### PR DESCRIPTION
**Pull request by jankleinert**
This is to fix https://github.com/openshift-labs/cloud-native-labs/issues/5.

Similar to what was submitted here: https://github.com/jbossdemocentral/coolstore-microservice/pull/120. I'm bringing this bower.json up to date with that one.

This should go in all branches - it's not specific to any one version of OpenShift.

### CODE REVIEW

**Comment by pprosser-redhat** [comment]
Hi Guys,

Thanks for fixing this. I can confirm that it works.

The only issue is that it has only been merged into the master branch which means that the lab guides are slightly incorrect as they describe using the branch aligned to the OCP version

Thanks

Phil.

**Comment by jankleinert** [comment]
I think I have merge privileges now, so I'll take care of that today.

**Comment by jankleinert** [comment]
@pprosser-redhat The other branches are updated now.

**Comment by pprosser-redhat** [comment]
Perfect, thanks Jan

**Pull request merged**
